version: "3.7"

services:
  db:
    image: postgres:11.5
    ports:
    - 5432:5432
    volumes:
    - ./data:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"