---
micronaut:
  application:
    name: micronaut-data-test-hibernate

---
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: password
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
      show_sql: true
      format_sql: true
